import { Company, User, UserRole, CompanyCategory, ContactType, Opportunity, OpportunityStatus, ConfidentialityMode } from '../types';

// Helper to parse strings
const parseList = (str: string) => str === 'N/D' ? [] : str.split(',').map(s => s.trim());

// --- 1. EXISTING DEMO DATA (REQUIRED FOR LOGIN) ---
const ORIGINAL_DEMO_COMPANIES: Company[] = [
  {
    id: 'c-claut',
    legalName: 'Cluster Automotriz de Nuevo León A.C.',
    tradeName: 'CLAUT',
    category: CompanyCategory.ACADEMIA,
    country: 'México',
    state: 'Nuevo León',
    city: 'Monterrey',
    websiteUrl: 'https://www.claut.com.mx',
    publicCoreSummary: 'Organización que impulsa la competitividad del sector automotriz.',
    publicCapabilities: ['Vinculación', 'Consultoría', 'Capacitación'],
    publicCertifications: [],
    isActive: true,
    isMemberClaut: true,
    profileCompletenessPercent: 100,
    contacts: [],
    createdAt: new Date().toISOString()
  },
  {
    id: 'c-oem-1',
    legalName: 'Kia México S.A. de C.V.',
    tradeName: 'KIA Motors',
    category: CompanyCategory.OEM,
    country: 'México',
    state: 'Nuevo León',
    city: 'Pesquería',
    websiteUrl: 'https://www.kia.com/mx',
    publicCoreSummary: 'Fabricante global de automóviles con planta de última generación en Pesquería.',
    publicCapabilities: ['Ensamble Final', 'Estampado', 'Soldadura', 'Pintura'],
    publicCertifications: ['ISO 14001', 'ISO 9001', 'IATF 16949'],
    isActive: true,
    isMemberClaut: true,
    profileCompletenessPercent: 100,
    contacts: [
      { id: 'ct-kia-1', companyId: 'c-oem-1', type: ContactType.PROCUREMENT, name: 'Roberto Compras', email: 'compras@kia.demo', position: 'Gerente Compras' }
    ],
    createdAt: new Date().toISOString()
  },
  {
    id: 'c-tier1-1',
    legalName: 'Metalmecanica Avanzada S.A. de C.V.',
    tradeName: 'Metalsa',
    category: CompanyCategory.TIER_I,
    country: 'México',
    state: 'Nuevo León',
    city: 'Apodaca',
    publicCoreSummary: 'Líderes en manufactura de chasis para vehículos ligeros y comerciales.',
    publicCapabilities: ['Estampado', 'Soldadura', 'Pintura E-coat', 'Diseño'],
    publicCertifications: ['IATF 16949', 'ISO 14001', 'Q1'],
    isActive: true,
    isMemberClaut: true,
    profileCompletenessPercent: 95,
    contacts: [
      { id: 'ct-met-1', companyId: 'c-tier1-1', type: ContactType.SALES, name: 'Ana Ventas', email: 'ventas@metalsa.demo', position: 'Key Account Manager' },
      { id: 'ct-met-2', companyId: 'c-tier1-1', type: ContactType.PROCUREMENT, name: 'Juan Abasto', email: 'compras@metalsa.demo', position: 'Sourcing Lead' }
    ],
    createdAt: new Date().toISOString()
  },
  {
    id: 'c-tier2-1',
    legalName: 'Plásticos Técnicos del Norte S.A.',
    tradeName: 'Plastec',
    category: CompanyCategory.TIER_II,
    country: 'México',
    state: 'Coahuila',
    city: 'Saltillo',
    publicCoreSummary: 'Inyección de plásticos de ingeniería para interiores y componentes funcionales.',
    publicCapabilities: ['Inyección de Plástico', 'Ensamble', 'Moldeo por inserción'],
    publicCertifications: ['ISO 9001', 'IATF 16949'],
    isActive: true,
    isMemberClaut: true,
    profileCompletenessPercent: 88,
    contacts: [
      { id: 'ct-pla-1', companyId: 'c-tier2-1', type: ContactType.SALES, name: 'Carlos Sales', email: 'ventas@plastec.demo', position: 'Gerente Ventas' }
    ],
    createdAt: new Date().toISOString()
  }
];

// --- 2. REAL COMPANIES FROM DATASET ---
const REAL_COMPANIES: Company[] = [
  {
    id: 'real-cat',
    legalName: 'Caterpillar Inc.',
    tradeName: 'Caterpillar',
    category: CompanyCategory.OEM,
    country: 'México',
    state: 'Nuevo León', // Assumed based on CLAUT context, usually has presence
    city: 'Monterrey',
    websiteUrl: 'https://www.cat.com/es_MX.html',
    publicCoreSummary: 'Diseña y fabrica maquinaria pesada, motores y equipos de construcción y minería.',
    publicProductsServicesSummary: 'Excavadoras, motoniveladoras, cargadores frontales, tractores de orugas, motores diésel.',
    publicCapabilities: ['Manufactura Pesada', 'Ensamble', 'Motores'],
    publicCertifications: [],
    employeesRange: '1000+',
    isActive: true,
    isMemberClaut: true,
    profileCompletenessPercent: 85,
    contacts: [],
    createdAt: new Date().toISOString()
  },
  {
    id: 'real-daimler',
    legalName: 'Daimler Truck / Mercedes-Benz Group',
    tradeName: 'Daimler Truck',
    category: CompanyCategory.OEM,
    country: 'México',
    state: 'Coahuila', // Derramadero plant context
    city: 'Saltillo',
    websiteUrl: 'https://www.daimlertruck.com',
    publicCoreSummary: 'Diseña, fabrica y comercializa camiones, autobuses y vehículos de lujo.',
    publicProductsServicesSummary: 'Camiones Freightliner, camiones Mercedes‑Benz, autobuses.',
    publicCapabilities: ['Ensamble Vehículos', 'Sistemas de Propulsión'],
    publicCertifications: ['IATF 16949'],
    isActive: true,
    isMemberClaut: true,
    profileCompletenessPercent: 80,
    contacts: [],
    createdAt: new Date().toISOString()
  },
  {
    id: 'real-navistar',
    legalName: 'Navistar International',
    tradeName: 'International Trucks',
    category: CompanyCategory.OEM,
    country: 'México',
    state: 'Nuevo León',
    city: 'Escobedo',
    websiteUrl: 'https://mexico.internationaltrucks.com',
    publicCoreSummary: 'Diseña, fabrica y vende camiones de carga, autobuses y motores diésel.',
    publicProductsServicesSummary: 'Camiones de carga pesada, autobuses, motores diésel.',
    publicCapabilities: ['Ensamble Camiones', 'Motores Diésel', 'Pintura'],
    publicCertifications: ['ISO 14001', 'ISO 9001'],
    isActive: true,
    isMemberClaut: true,
    profileCompletenessPercent: 90,
    contacts: [],
    createdAt: new Date().toISOString()
  },
  {
    id: 'real-johndeere',
    legalName: 'John Deere',
    tradeName: 'John Deere',
    category: CompanyCategory.OEM,
    country: 'México',
    state: 'Nuevo León',
    city: 'San Pedro Garza García',
    websiteUrl: 'https://www.deere.com.mx/es/index.html',
    publicCoreSummary: 'Produce maquinaria agrícola, equipos de construcción y motores.',
    publicProductsServicesSummary: 'Tractores, cosechadoras, excavadoras, skid steers, motores.',
    publicCapabilities: ['Manufactura Agrícola', 'Hidráulica', 'Electrónica'],
    publicCertifications: [],
    isActive: true,
    isMemberClaut: true,
    profileCompletenessPercent: 85,
    contacts: [],
    createdAt: new Date().toISOString()
  },
  {
    id: 'real-polaris',
    legalName: 'Polaris Off Road Vehicles',
    tradeName: 'Polaris',
    category: CompanyCategory.OEM,
    country: 'México',
    state: 'Nuevo León',
    city: 'Apodaca',
    websiteUrl: 'https://polaris.com',
    publicCoreSummary: 'Desarrolla y comercializa vehículos todoterreno, motos de nieve y motocicletas.',
    publicProductsServicesSummary: 'Vehículos RZR, Ranger, Sportsman, motos de nieve.',
    publicCapabilities: ['Ensamble Vehículos', 'Soldadura', 'Pintura'],
    publicCertifications: [],
    isActive: true,
    isMemberClaut: true,
    profileCompletenessPercent: 85,
    contacts: [],
    createdAt: new Date().toISOString()
  },
  {
    id: 'real-accuride',
    legalName: 'Accuride',
    tradeName: 'Accuride',
    category: CompanyCategory.TIER_I,
    country: 'México',
    state: 'Nuevo León',
    city: 'Ciénega de Flores',
    websiteUrl: 'https://www.accuridecorp.com',
    publicCoreSummary: 'Diseña y fabrica ruedas y componentes de rueda para vehículos comerciales.',
    publicProductsServicesSummary: 'Ruedas de acero, ruedas de aluminio, componentes de rueda.',
    publicCapabilities: ['Estampado', 'Soldadura', 'Forja'],
    publicCertifications: ['ISO 9001:2015', 'IATF 16949:2016'],
    employeesRange: '1000+',
    isActive: true,
    isMemberClaut: true,
    profileCompletenessPercent: 95,
    contacts: [{ id: 'ct-acc-1', companyId: 'real-accuride', type: ContactType.SALES, name: 'Sales Contact', email: 'apfaffma@accuridecorp.com' }],
    createdAt: new Date().toISOString()
  },
  {
    id: 'real-brembo',
    legalName: 'Brembo',
    tradeName: 'Brembo',
    category: CompanyCategory.TIER_I,
    country: 'México',
    state: 'Nuevo León',
    city: 'Apodaca',
    websiteUrl: 'https://www.brembo.com',
    publicCoreSummary: 'Diseña y fabrica sistemas de frenos y componentes de alto rendimiento.',
    publicProductsServicesSummary: 'Sistemas de frenos, discos, pinzas, componentes de suspensión.',
    publicCapabilities: ['Fundición', 'Maquinado', 'Ensamble'],
    publicCertifications: ['QS9000', 'ISO 9001'],
    employeesRange: '1000+',
    isActive: true,
    isMemberClaut: true,
    profileCompletenessPercent: 90,
    contacts: [],
    createdAt: new Date().toISOString()
  },
  {
    id: 'real-clarios',
    legalName: 'Clarios',
    tradeName: 'Clarios',
    category: CompanyCategory.TIER_I,
    country: 'México',
    state: 'Nuevo León',
    city: 'García',
    websiteUrl: 'https://www.clarios.com',
    publicCoreSummary: 'Líder mundial en soluciones avanzadas de baterías de baja tensión.',
    publicProductsServicesSummary: 'Baterías de plomo-ácido, AGM, iones de litio.',
    publicCapabilities: ['Manufactura Baterías', 'Reciclaje', 'Química'],
    publicCertifications: ['IATF 16949', 'ISO 14001'],
    employeesRange: '1000+',
    isActive: true,
    isMemberClaut: true,
    profileCompletenessPercent: 92,
    contacts: [{ id: 'ct-clar-1', companyId: 'real-clarios', type: ContactType.SALES, name: 'Christian Riedel', email: 'christian.m.riedel@clarios.com' }],
    createdAt: new Date().toISOString()
  },
  {
    id: 'real-denso',
    legalName: 'Denso',
    tradeName: 'Denso',
    category: CompanyCategory.TIER_I,
    country: 'México',
    state: 'Nuevo León',
    city: 'Apodaca',
    websiteUrl: 'https://www.denso.com',
    publicCoreSummary: 'Desarrollo y fabricación de sistemas térmicos, tren motriz y electrónica.',
    publicProductsServicesSummary: 'Sistemas de aire acondicionado, radiadores, alternadores, sensores.',
    publicCapabilities: ['Electrónica', 'Inyección Plástico', 'Ensamble'],
    publicCertifications: ['IATF 16949', 'ISO 14001'],
    employeesRange: '1000+',
    isActive: true,
    isMemberClaut: true,
    profileCompletenessPercent: 90,
    contacts: [],
    createdAt: new Date().toISOString()
  },
  {
    id: 'real-forvia',
    legalName: 'Forvia (Faurecia/HELLA)',
    tradeName: 'Forvia',
    category: CompanyCategory.TIER_I,
    country: 'México',
    state: 'Nuevo León',
    city: 'Apodaca',
    websiteUrl: 'https://www.forvia.com',
    publicCoreSummary: 'Proveedor global de asientos, interiores, electrónica y sistemas de escape.',
    publicProductsServicesSummary: 'Asientos, paneles de instrumentos, sistemas de iluminación, sensores.',
    publicCapabilities: ['Inyección Plástico', 'Cut & Sew', 'Electrónica', 'Ensamble'],
    publicCertifications: ['ISO 9001', 'IATF 16949'],
    employeesRange: '1000+',
    isActive: true,
    isMemberClaut: true,
    profileCompletenessPercent: 95,
    contacts: [],
    createdAt: new Date().toISOString()
  },
  {
    id: 'real-nemak',
    legalName: 'Nemak',
    tradeName: 'Nemak',
    category: CompanyCategory.TIER_I,
    country: 'México',
    state: 'Nuevo León',
    city: 'García',
    websiteUrl: 'https://www.nemak.com',
    publicCoreSummary: 'Soluciones de aligeramiento para la industria automotriz global (Fundición).',
    publicProductsServicesSummary: 'Cabezas de motor, monobloques, componentes de transmisión, estructuras.',
    publicCapabilities: ['Fundición Aluminio', 'Maquinado', 'Tratamiento Térmico'],
    publicCertifications: ['IATF 16949', 'ISO 14001'],
    employeesRange: '1000+',
    isActive: true,
    isMemberClaut: true,
    profileCompletenessPercent: 98,
    contacts: [],
    createdAt: new Date().toISOString()
  },
  {
    id: 'real-zf',
    legalName: 'ZF Friedrichshafen',
    tradeName: 'ZF Group',
    category: CompanyCategory.TIER_I,
    country: 'México',
    state: 'Nuevo León',
    city: 'Guadalupe',
    websiteUrl: 'https://www.zf.com',
    publicCoreSummary: 'Diseño y fabricación de transmisiones, chasis y sistemas de seguridad.',
    publicProductsServicesSummary: 'Transmisiones automáticas, bolsas de aire, sistemas de dirección.',
    publicCapabilities: ['Maquinado', 'Ensamble', 'Electrónica'],
    publicCertifications: ['IATF 16949', 'ISO 9001'],
    employeesRange: '1000+',
    isActive: true,
    isMemberClaut: true,
    profileCompletenessPercent: 90,
    contacts: [],
    createdAt: new Date().toISOString()
  },
  {
    id: 'real-yazaki',
    legalName: 'Yazaki',
    tradeName: 'Yazaki',
    category: CompanyCategory.TIER_I,
    country: 'México',
    state: 'Nuevo León',
    city: 'Monterrey',
    websiteUrl: 'https://www.yazaki-group.com',
    publicCoreSummary: 'Diseño y fabricación de arneses de cableado y componentes eléctricos.',
    publicProductsServicesSummary: 'Arneses de cables, conectores, instrumentación.',
    publicCapabilities: ['Ensamble Manual', 'Corte y Desforre', 'Inyección Plástico'],
    publicCertifications: ['IATF 16949', 'ISO 14001'],
    employeesRange: '1000+',
    isActive: true,
    isMemberClaut: true,
    profileCompletenessPercent: 88,
    contacts: [],
    createdAt: new Date().toISOString()
  },
  {
    id: 'real-aam',
    legalName: 'AAM',
    tradeName: 'American Axle & Manufacturing',
    category: CompanyCategory.TIER_II,
    country: 'México',
    state: 'Nuevo León',
    city: 'Ciénega de Flores',
    websiteUrl: 'https://www.aam.com',
    publicCoreSummary: 'Diseño, ingeniería y fabricación de componentes de tren motriz (driveline).',
    publicProductsServicesSummary: 'Ejes, flechas de transmisión, módulos AWD/RWD.',
    publicCapabilities: ['Forja', 'Maquinado', 'Tratamiento Térmico', 'Ensamble'],
    publicCertifications: ['ISO/TS 16949'],
    employeesRange: '1000+',
    isActive: true,
    isMemberClaut: true,
    profileCompletenessPercent: 85,
    contacts: [{ id: 'ct-aam-1', companyId: 'real-aam', type: ContactType.GENERAL, name: 'Investor Relations', email: 'investorrelations@aam.com' }],
    createdAt: new Date().toISOString()
  },
  {
    id: 'real-aceroprime',
    legalName: 'Acero Prime',
    tradeName: 'Acero Prime',
    category: CompanyCategory.TIER_II,
    country: 'México',
    state: 'San Luis Potosí', // Has presence in various
    city: 'San Luis Potosí',
    websiteUrl: 'https://aceroprime.com',
    publicCoreSummary: 'Procesamiento de acero y servicios logísticos.',
    publicProductsServicesSummary: 'Corte longitudinal y transversal, nivelado, multiblanking.',
    publicCapabilities: ['Corte Acero', 'Logística', 'Almacenaje'],
    publicCertifications: ['ISO/TS 16949'],
    employeesRange: '201-500',
    isActive: true,
    isMemberClaut: true,
    profileCompletenessPercent: 80,
    contacts: [{ id: 'ct-aceroprime', companyId: 'real-aceroprime', type: ContactType.SALES, name: 'Ventas', email: 'contact@aceroprime.com' }],
    createdAt: new Date().toISOString()
  },
  {
    id: 'real-axalta',
    legalName: 'Axalta',
    tradeName: 'Axalta Coating Systems',
    category: CompanyCategory.TIER_II,
    country: 'México',
    state: 'Estado de México',
    city: 'Tlalnepantla',
    websiteUrl: 'https://www.axalta.com',
    publicCoreSummary: 'Diseño y producción de recubrimientos y pinturas de alto desempeño.',
    publicProductsServicesSummary: 'Pinturas líquidas, recubrimientos en polvo, e-coat.',
    publicCapabilities: ['Química', 'Formulación', 'Colorimetría'],
    publicCertifications: [],
    employeesRange: '1000+',
    isActive: true,
    isMemberClaut: true,
    profileCompletenessPercent: 88,
    contacts: [{ id: 'ct-axalta', companyId: 'real-axalta', type: ContactType.GENERAL, name: 'Info', email: 'info.mx@axalta.com' }],
    createdAt: new Date().toISOString()
  },
  {
    id: 'real-alian',
    legalName: 'Alian',
    tradeName: 'Alian Plastics',
    category: CompanyCategory.TIER_II,
    country: 'México',
    state: 'Nuevo León',
    city: 'Monterrey',
    websiteUrl: 'https://www.alian.mx',
    publicCoreSummary: 'Diseño y fabricación de piezas plásticas mediante inyección.',
    publicProductsServicesSummary: 'Componentes plásticos automotrices, insert molding, decoración.',
    publicCapabilities: ['Inyección Plástico', 'Soldadura Ultrasónica', 'Ensamble'],
    publicCertifications: ['IATF 16949', 'ISO 9001', 'ISO 14001'],
    employeesRange: '201-500',
    isActive: true,
    isMemberClaut: true,
    profileCompletenessPercent: 85,
    contacts: [{ id: 'ct-alian', companyId: 'real-alian', type: ContactType.SALES, name: 'Ventas', email: 'sales@alian.mx' }],
    createdAt: new Date().toISOString()
  },
  {
    id: 'real-b2',
    legalName: 'B2 Solutions',
    tradeName: 'B2 Solutions',
    category: CompanyCategory.TIER_II,
    country: 'México',
    state: 'Nuevo León',
    city: 'Monterrey',
    websiteUrl: 'https://b2solutions.mx',
    publicCoreSummary: 'Diseña y manufactura sistemas de automatización, inspección y poka‑yokes.',
    publicProductsServicesSummary: 'Estaciones de ensamble, sistemas de visión, robótica.',
    publicCapabilities: ['Automatización', 'Integración', 'Diseño Mecánico'],
    publicCertifications: [],
    employeesRange: '51-200',
    isActive: true,
    isMemberClaut: true,
    profileCompletenessPercent: 75,
    contacts: [{ id: 'ct-b2', companyId: 'real-b2', type: ContactType.SALES, name: 'Ventas', email: 'ventas@b2solutions.mx' }],
    createdAt: new Date().toISOString()
  },
  {
    id: 'real-connor',
    legalName: 'Connor Manufacturing',
    tradeName: 'Connor',
    category: CompanyCategory.TIER_II,
    country: 'México',
    state: 'Nuevo León',
    city: 'Apodaca',
    websiteUrl: 'https://www.connorms.com',
    publicCoreSummary: 'Provee soluciones de busbars y componentes metálicos para movilidad eléctrica.',
    publicProductsServicesSummary: 'Busbars, clips, piezas estampadas de precisión.',
    publicCapabilities: ['Estampado', 'Fabricación Metálica', 'Ensamble'],
    publicCertifications: [],
    employeesRange: '501-1000',
    isActive: true,
    isMemberClaut: true,
    profileCompletenessPercent: 82,
    contacts: [{ id: 'ct-connor', companyId: 'real-connor', type: ContactType.SALES, name: 'Mexico Sales', email: 'MexicoSales@ConnorMS.com' }],
    createdAt: new Date().toISOString()
  },
  {
    id: 'real-tarimas',
    legalName: 'Tarimas & Empaques Santa Catarina',
    tradeName: 'Tarimas & Empaques',
    category: CompanyCategory.TIER_II,
    country: 'México',
    state: 'Nuevo León',
    city: 'Santa Catarina',
    websiteUrl: 'https://www.tarimasyempaques.com',
    publicCoreSummary: 'Diseña y fabrica soluciones de empaque para proteger y transportar productos.',
    publicProductsServicesSummary: 'Tarimas de madera, empaques personalizados, embalajes industriales.',
    publicCapabilities: ['Empaque', 'Logística', 'Carpintería Industrial'],
    publicCertifications: [],
    employeesRange: '201-500',
    isActive: true,
    isMemberClaut: true,
    profileCompletenessPercent: 80,
    contacts: [],
    createdAt: new Date().toISOString()
  },
  {
      id: 'real-avery',
      legalName: 'Avery Dennison',
      tradeName: 'Avery Dennison',
      category: CompanyCategory.TIER_II,
      country: 'México',
      state: 'Querétaro',
      city: 'Querétaro',
      websiteUrl: 'https://www.averydennison.com',
      publicCoreSummary: 'Fabricación de materiales autoadheribles y soluciones RFID.',
      publicProductsServicesSummary: 'Etiquetas, cintas adhesivas, tags RFID.',
      publicCapabilities: ['Impresión', 'Adhesivos', 'RFID'],
      publicCertifications: [],
      employeesRange: '1000+',
      isActive: true,
      isMemberClaut: true,
      profileCompletenessPercent: 85,
      contacts: [{ id: 'ct-ad', companyId: 'real-avery', type: ContactType.GENERAL, name: 'Info', email: 'ad.mx@averydennison.com' }],
      createdAt: new Date().toISOString()
  },
  {
      id: 'real-emsa',
      legalName: 'EMSA Mofles',
      tradeName: 'EMSA',
      category: CompanyCategory.TIER_II,
      country: 'México',
      state: 'Nuevo León',
      city: 'Monterrey',
      websiteUrl: 'https://emsamofles.com',
      publicCoreSummary: 'Diseña y fabrica sistemas de escape y convertidores catalíticos.',
      publicProductsServicesSummary: 'Mofles, tubería de escape, catalizadores.',
      publicCapabilities: ['Soldadura', 'Doblado de Tubo', 'Ensamble'],
      publicCertifications: [],
      employeesRange: '51-200',
      isActive: true,
      isMemberClaut: true,
      profileCompletenessPercent: 78,
      contacts: [],
      createdAt: new Date().toISOString()
  }
];

export const SEED_COMPANIES = [...ORIGINAL_DEMO_COMPANIES, ...REAL_COMPANIES];

export const SEED_USERS: User[] = [
  {
    id: 'u-super',
    name: 'Admin CLAUT',
    email: 'admin@claut.demo',
    role: UserRole.SUPERADMIN_CLAUT,
    passwordHash: '123456'
  },
  {
    id: 'u-coord',
    name: 'Claudia Coordinadora',
    email: 'claudia@claut.com.mx',
    role: UserRole.COORDINADOR_CLAUT,
    passwordHash: '123456'
  },
  {
    id: 'u-buyer-kia',
    companyId: 'c-oem-1',
    name: 'Roberto KIA',
    email: 'compras@kia.demo',
    role: UserRole.COMPRADOR,
    passwordHash: '123456'
  },
  {
    id: 'u-buyer-metalsa',
    companyId: 'c-tier1-1',
    name: 'Juan Metalsa',
    email: 'compras@metalsa.demo',
    role: UserRole.COMPRADOR,
    passwordHash: '123456'
  },
  {
    id: 'u-supplier-plastec',
    companyId: 'c-tier2-1',
    name: 'Carlos Plastec',
    email: 'ventas@plastec.demo',
    role: UserRole.PROVEEDOR,
    passwordHash: '123456'
  }
];

export const SEED_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'OP-2024-001',
    createdByUserId: 'u-buyer-kia',
    buyerCompanyId: 'c-oem-1',
    title: 'Soportes de Motor (Aluminio Fundido)',
    summary: 'Requerimos proveedor Tier 1 o 2 con capacidad de fundición de aluminio y maquinado para soportes de motor Gen3.',
    quantity: '50,000 pzas/año',
    specifications: 'Aleación A380, prueba de rayos X requerida al 100%.',
    requiredCertifications: ['IATF 16949'],
    otherRequirements: 'Localización en noreste deseable.',
    confidentialityMode: ConfidentialityMode.SHOW_COMPANY,
    applicationDeadlineAt: new Date(Date.now() + 15 * 86400000).toISOString(),
    status: OpportunityStatus.OPEN,
    aiDetectedCapabilities: ['Fundición', 'Maquinado CNC'],
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString()
  },
  {
    id: 'OP-2024-002',
    createdByUserId: 'u-buyer-metalsa',
    buyerCompanyId: 'c-tier1-1',
    title: 'Servicio de Recubrimiento E-Coat',
    summary: 'Buscamos capacidad externa para overflow de pintura E-Coat en componentes estructurales medianos.',
    quantity: 'Lotes de 5,000 pzas',
    specifications: 'Resistencia a corrosión > 1000 hrs cámara salina.',
    requiredCertifications: ['ISO 9001'],
    otherRequirements: '',
    confidentialityMode: ConfidentialityMode.ANONYMOUS_TO_PROVIDERS,
    applicationDeadlineAt: new Date(Date.now() + 5 * 86400000).toISOString(),
    status: OpportunityStatus.OPEN,
    aiDetectedCapabilities: ['Pintura', 'Recubrimientos'],
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString()
  }
];
